// export { default as Button } from './src/button'

export { default as createFromIconFontCN } from './src/icon/IconFont'
export { default as Divider } from './src/divider'
export { ConfigProvider } from './src/config-provider'
export { default as theme } from './src/theme'
export { default as Flex } from './src/flex'
export type { FlexProps } from './src/flex/interface'
export { default as Space } from './src/space'
export type { SpaceProps } from './src/space'
